
package Interface;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import domain.Cuadricula;
import javafx.scene.shape.Mesh;
/**
 *
 * @author jeanp
 */
public class MainFrame extends javax.swing.JFrame {
    
    private FileNameExtensionFilter fileFilter = new FileNameExtensionFilter("Imagen archivos", "jpg");
    String  imageRoute;
    
    public MainFrame() {
        initComponents();
        //centrar el frame
        this.setLocationRelativeTo(null);
        
        

    }
    
    //metodo para retornar el valor y poder cambiar el icono del frame
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("Images/mainIcon.png"));


        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_mainPanel = new javax.swing.JPanel();
        jb_addImage = new javax.swing.JButton();
        jb_close = new javax.swing.JButton();
        jb_minimize = new javax.swing.JButton();
        js_separator = new javax.swing.JSeparator();
        jl_showImage1 = new javax.swing.JLabel();
        jl_showImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);

        jp_mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        jp_mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_addImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Add_Image_50px_1.png"))); // NOI18N
        jb_addImage.setBorderPainted(false);
        jb_addImage.setContentAreaFilled(false);
        jb_addImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_addImageMouseClicked(evt);
            }
        });
        jb_addImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_addImageActionPerformed(evt);
            }
        });
        jp_mainPanel.add(jb_addImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 40));

        jb_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Delete_25px.png"))); // NOI18N
        jb_close.setBorderPainted(false);
        jb_close.setContentAreaFilled(false);
        jb_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_closeActionPerformed(evt);
            }
        });
        jp_mainPanel.add(jb_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 0, 30, 30));

        jb_minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Minimize_Window_25px.png"))); // NOI18N
        jb_minimize.setBorderPainted(false);
        jb_minimize.setContentAreaFilled(false);
        jb_minimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_minimizeActionPerformed(evt);
            }
        });
        jp_mainPanel.add(jb_minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 0, 30, 30));

        js_separator.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jp_mainPanel.add(js_separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 10, 650));

        jl_showImage1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jp_mainPanel.add(jl_showImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 70, 450, 520));

        jl_showImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jp_mainPanel.add(jl_showImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 450, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_addImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_addImageMouseClicked
        JFileChooser jfc = new JFileChooser();
        jfc.setFileFilter(fileFilter);
        
        //abrir dialogo para escojer las imagenenes
        int option = jfc.showOpenDialog(this);
        
        //cuando se da click al boton
        if(option==JFileChooser.APPROVE_OPTION){
            //ibbtener el nombre del archivo que se selecciono
            String getFileName=jfc.getSelectedFile().getPath();
            
            //direccion donde se guardara la imagen
            String getFileDirection = jfc.getSelectedFile().toString();
            jl_showImage.setIcon(new ImageIcon(getFileName));
            ImageIcon icon = new ImageIcon(getFileName);
            //obtiene la imagen del icono
            Image img = icon.getImage();
            //cambia el tamaño de la imagen 
            Image newImg = img.getScaledInstance(jl_showImage.getWidth(), jl_showImage.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon newIcon = new ImageIcon(newImg);
            
            //se pone la nueva imagen en el label
            jl_showImage.setIcon(newIcon);
            jl_showImage.setSize(155,175);
            //jl_showImage.setText(getFileName);
            
            imageRoute="";
            
            
        }
        
        
    }//GEN-LAST:event_jb_addImageMouseClicked

    //cierra la ventana y termina todos los procesos
    private void jb_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_closeActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jb_closeActionPerformed

    //minimiza la ventana
    private void jb_minimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_minimizeActionPerformed
        this.setState(MainFrame.ICONIFIED);
    }//GEN-LAST:event_jb_minimizeActionPerformed

    private void jb_addImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_addImageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_addImageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jb_addImage;
    private javax.swing.JButton jb_close;
    private javax.swing.JButton jb_minimize;
    private javax.swing.JLabel jl_showImage;
    private javax.swing.JLabel jl_showImage1;
    private javax.swing.JPanel jp_mainPanel;
    private javax.swing.JSeparator js_separator;
    // End of variables declaration//GEN-END:variables
}
